package com.adnanumar.task_manager.service.impl;

import com.adnanumar.task_manager.entity.Project;
import com.adnanumar.task_manager.entity.Task;
import com.adnanumar.task_manager.entity.User;
import com.adnanumar.task_manager.error.BadRequestException;
import com.adnanumar.task_manager.error.ResourceNotFoundException;
import com.adnanumar.task_manager.repository.ProjectMemberRepository;
import com.adnanumar.task_manager.repository.ProjectRepository;
import com.adnanumar.task_manager.repository.UserRepository;
import com.adnanumar.task_manager.service.ReportService;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.UnitValue;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public class ReportServiceImpl implements ReportService {

    ProjectRepository projectRepository;
    UserRepository userRepository;
    ProjectMemberRepository projectMemberRepository;

    @Override
    public ByteArrayInputStream exportProjectTasksToExcel(Long projectId, String email) {
        log.info("Exporting tasks to Excel for project {} by user {}", projectId, email);
        
        User user = getUserByEmailOrThrow(email);
        Project project = getProjectOrThrow(projectId);
        assertMembership(projectId, user.getId());

        List<Task> tasks = project.getTasks();

        try (Workbook workbook = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Sheet sheet = workbook.createSheet("Tasks");

            // Header row
            Row headerRow = sheet.createRow(0);
            String[] columns = {"ID", "Title", "Description", "Status", "Priority", "Due Date", "Assigned To"};
            
            CellStyle headerCellStyle = workbook.createCellStyle();
            Font headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerCellStyle.setFont(headerFont);

            for (int i = 0; i < columns.length; i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(columns[i]);
                cell.setCellStyle(headerCellStyle);
            }

            // Data rows
            int rowIdx = 1;
            for (Task task : tasks) {
                Row row = sheet.createRow(rowIdx++);
                row.createCell(0).setCellValue(task.getId());
                row.createCell(1).setCellValue(task.getTitle());
                row.createCell(2).setCellValue(task.getDescription());
                row.createCell(3).setCellValue(task.getStatus().name());
                row.createCell(4).setCellValue(task.getPriority().name());
                row.createCell(5).setCellValue(task.getDueDate() != null ? task.getDueDate().toString() : "");
                row.createCell(6).setCellValue(task.getAssignedTo() != null ? task.getAssignedTo().getName() : "Unassigned");
            }

            for (int i = 0; i < columns.length; i++) {
                sheet.autoSizeColumn(i);
            }

            workbook.write(out);
            return new ByteArrayInputStream(out.toByteArray());
        } catch (IOException e) {
            log.error("Failed to generate Excel report", e);
            throw new RuntimeException("Fail to import data to Excel file: " + e.getMessage());
        }
    }

    @Override
    public ByteArrayInputStream exportProjectTasksToPdf(Long projectId, String email) {
        log.info("Exporting tasks to PDF for project {} by user {}", projectId, email);
        
        User user = getUserByEmailOrThrow(email);
        Project project = getProjectOrThrow(projectId);
        assertMembership(projectId, user.getId());

        List<Task> tasks = project.getTasks();

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(out);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);

        document.add(new Paragraph("Project Tasks Report: " + project.getName()).setBold().setFontSize(18));
        document.add(new Paragraph("Generated by: " + user.getName()));
        document.add(new Paragraph("\n"));

        float[] columnWidths = {1, 3, 2, 2, 2};
        Table table = new Table(UnitValue.createPointArray(columnWidths));
        table.setWidth(UnitValue.createPercentValue(100));

        table.addHeaderCell("ID");
        table.addHeaderCell("Title");
        table.addHeaderCell("Status");
        table.addHeaderCell("Priority");
        table.addHeaderCell("Due Date");

        for (Task task : tasks) {
            table.addCell(task.getId().toString());
            table.addCell(task.getTitle());
            table.addCell(task.getStatus().name());
            table.addCell(task.getPriority().name());
            table.addCell(task.getDueDate() != null ? task.getDueDate().toString() : "N/A");
        }

        document.add(table);
        document.close();

        return new ByteArrayInputStream(out.toByteArray());
    }

    // ─── Helpers ────────────────────────────────────────────────────────────────

    private User getUserByEmailOrThrow(String email) {
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException("User", email));
    }

    private Project getProjectOrThrow(Long projectId) {
        return projectRepository.findById(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Project", projectId.toString()));
    }

    private void assertMembership(Long projectId, Long userId) {
        if (!projectMemberRepository.existsByUserIdAndProjectId(userId, projectId)) {
            throw new BadRequestException("You are not a member of this project");
        }
    }
}
